# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Node', max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(max_length=5)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Nodename')),
            ],
        ),
    ]
