# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodename',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nodename',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
